itoolnew/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scorecard.urls')),
]

scorecard/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import logout_then_login

from scorecard.views.index import index
from scorecard.views.productivity import productivity
from scorecard.views.penetration import penetration
from scorecard.views.six import six
from scorecard.views.assortment import assortment

app_name = 'scorecard'
urlpatterns = [
    path('', index, name='index'),
    path('productivity/', productivity, name='productivity'),
    path('penetration/', penetration, name='penetration'),
    path('six/', six, name='six'),
    path('assortment/', assortment, name='assortment'),
]

scorecard/models.py
from django.db import models

# Create your models here.

scorecard/views.py
from django.shortcuts import render

# Create your views here.

scorecard/views/assortment.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response, redirect, render, get_object_or_404
from django.template import RequestContext
from django.http import *
from django.urls import reverse, reverse_lazy
from django.core.exceptions import SuspiciousOperation
from django.views import generic
from django.shortcuts import get_object_or_404

import json

def assortment(request):
    context={}
    context['app']           = 'scorecard'
    context['app_name']      = 'Scorecard'
    context['seccion']       = '%s_assortment' % (context['app'])
    context['logos']         = True
    context['navbar']        = True
    context['menu']          = True
    context['regresar']      = True
    context['url_regresar']  = reverse('scorecard:index')
    context['botones_nav']   = True
    context['titulo']        = 'Assortment'
    context['subtitulo']     = 'Subtítulo'
    context['footer']        = True

    return render(request, 'scorecard/assortment.html', context)

scorecard/views/index.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response, redirect, render, get_object_or_404
from django.template import RequestContext
from django.http import *
from django.urls import reverse, reverse_lazy
from django.core.exceptions import SuspiciousOperation
from django.views import generic
from django.shortcuts import get_object_or_404

import json

def index(request):
    context={}
    context['app']           = 'scorecard'
    context['app_name']      = 'Scorecard'
    context['seccion']       = '%s_index' % (context['app'])
    context['logos']         = True
    context['navbar']        = True
    context['menu']          = True
    context['regresar']      = True
    context['url_regresar']  = reverse('scorecard:index')
    context['botones_nav']   = True
    context['titulo']        = 'Bienvenido'
    context['subtitulo']     = 'Haz click en uno de los botones superiores para ir al módulo correspondiente'
    context['footer']        = True

    return render(request, 'scorecard/index.html', context)

scorecard/views/penetration.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response, redirect, render, get_object_or_404
from django.template import RequestContext
from django.http import *
from django.urls import reverse, reverse_lazy
from django.core.exceptions import SuspiciousOperation
from django.views import generic
from django.shortcuts import get_object_or_404

import json

def penetration(request):
    context={}
    context['app']           = 'scorecard'
    context['app_name']      = 'Scorecard'
    context['seccion']       = '%s_penetration' % (context['app'])
    context['logos']         = True
    context['navbar']        = True
    context['menu']          = True
    context['regresar']      = True
    context['url_regresar']  = reverse('scorecard:index')
    context['botones_nav']   = True
    context['titulo']        = 'Penetration'
    context['subtitulo']     = 'Selecciona una opción para filtrar'
    context['footer']        = True

    return render(request, 'scorecard/penetration.html', context)

scorecard/views/productivity.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response, redirect, render, get_object_or_404
from django.template import RequestContext
from django.http import *
from django.urls import reverse, reverse_lazy
from django.core.exceptions import SuspiciousOperation
from django.views import generic
from django.shortcuts import get_object_or_404

import json

def productivity(request):
    context={}
    context['app']           = 'scorecard'
    context['app_name']      = 'Scorecard'
    context['seccion']       = '%s_productivity' % (context['app'])
    context['logos']         = True
    context['navbar']        = True
    context['menu']          = True
    context['regresar']      = True
    context['url_regresar']  = reverse('scorecard:index')
    context['botones_nav']   = True
    context['titulo']        = 'Reportes iniciativas - Dashboard - One Page'
    context['subtitulo']     = 'Iniciativas Productividad'
    context['footer']        = True

    return render(request, 'scorecard/productivity.html', context)

scorecard/views/six.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response, redirect, render, get_object_or_404
from django.template import RequestContext
from django.http import *
from django.urls import reverse, reverse_lazy
from django.core.exceptions import SuspiciousOperation
from django.views import generic
from django.shortcuts import get_object_or_404

import json

def six(request):
    context={}
    context['app']           = 'scorecard'
    context['app_name']      = 'Scorecard'
    context['seccion']       = '%s_six' % (context['app'])
    context['logos']         = True
    context['navbar']        = True
    context['menu']          = True
    context['regresar']      = True
    context['url_regresar']  = reverse('scorecard:index')
    context['botones_nav']   = True
    context['titulo']        = 'Six'
    context['subtitulo']     = 'Subtítulo'
    context['footer']        = True

    return render(request, 'scorecard/six.html', context)

scorecard/templates/scorecard/assortment.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block head %}
{% endblock %}

{% block content %}
<div class="row justify-content-center mt-4 mb-5">
  <div class="col-xl-10 col-lg-10 col-md-10 col-sm-12 col-12">
    {% include 'includes/titulo.html' %}
  </div><!-- /.col-xl-10 -->
</div><!-- /.row -->
{% endblock %}

{% block footercode %}
{% endblock %}

scorecard/templates/scorecard/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block head %}
{% endblock %}

{% block content %}
<div class="row justify-content-center mt-4 mb-5">
  <div class="col-xl-10 col-lg-10 col-md-10 col-sm-12 col-12">
    {% include 'includes/titulo.html' %}
  </div><!-- /.col-xl-10 -->
</div><!-- /.row -->
{% endblock %}

{% block footercode %}
{% endblock %}

scorecard/templates/scorecard/six.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block head %}
{% endblock %}

{% block content %}
<div class="row justify-content-center mt-4 mb-5">
  <div class="col-xl-10 col-lg-10 col-md-10 col-sm-12 col-12">
    {% include 'includes/titulo.html' %}
  </div><!-- /.col-xl-10 -->
</div><!-- /.row -->
{% endblock %}

{% block footercode %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include 'includes/head.html' %}
  </head>
  <body>
    {% if navbar %}
    {% include 'includes/navbar.html' %}
    {% endif %}
    <!-- =================== -->
    <!-- ===* CONTENIDO *=== -->
    <!-- =================== -->
    <div class="col-12">
      {% block content %}
      {% endblock %}
    </div><!-- /.col-12 -->
    <!-- =================== -->
    <!-- =================== -->
    <!-- =================== -->
    {% include 'includes/footer.html' %}
    {% include 'includes/scripts.html' %}
    {% block footercode %}
    {% endblock %}
  </body>

templates/includes/footer.html
{% load staticfiles %}
<!-- ===* Footer *=== -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-bottom">
  <div class="row">
    <div class="container text-white">
      <small>Copyright © 2018&nbsp;&nbsp;|&nbsp;&nbsp;<a href="https://htatec.com" target="_blank"><img src="imgs/logo_HTA_web.png" style="max-height:20px; width:auto;"></a>&nbsp;&nbsp;All rights reserved.</small>
    </div><!-- /.container -->
  </div><!-- /.row -->
</nav>

templates/includes/head.html
{% load staticfiles %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta http-equiv="cache-control" content="max-age=0" />
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="expires" content="0" />
<meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
<meta http-equiv="pragma" content="no-cache" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="iTool">
<meta name="author" content="HTA Developers">
<link rel="apple-touch-icon" sizes="57x57" href="{% static 'base/imgs/favicon/apple-icon-57x57.png' %}">
<link rel="apple-touch-icon" sizes="60x60" href="{% static 'base/imgs/favicon/apple-icon-60x60.png' %}">
<link rel="apple-touch-icon" sizes="72x72" href="{% static 'base/imgs/favicon/apple-icon-72x72.png' %}">
<link rel="apple-touch-icon" sizes="76x76" href="{% static 'base/imgs/favicon/apple-icon-76x76.png' %}">
<link rel="apple-touch-icon" sizes="114x114" href="{% static 'base/imgs/favicon/apple-icon-114x114.png' %}">
<link rel="apple-touch-icon" sizes="120x120" href="{% static 'base/imgs/favicon/apple-icon-120x120.png' %}">
<link rel="apple-touch-icon" sizes="144x144" href="{% static 'base/imgs/favicon/apple-icon-144x144.png' %}">
<link rel="apple-touch-icon" sizes="152x152" href="{% static 'base/imgs/favicon/apple-icon-152x152.png' %}">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'base/imgs/favicon/apple-icon-180x180.png' %}">
<link rel="icon" type="image/png" sizes="192x192"  href="{% static 'base/imgs/favicon/android-icon-192x192.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'base/imgs/favicon/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="96x96" href="{% static 'base/imgs/favicon/favicon-96x96.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'base/imgs/favicon/favicon-16x16.png' %}">
<link rel="manifest" href="{% static 'base/imgs/favicon/manifest.json' %}">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="{% static 'base/imgs/favicon/ms-icon-144x144.png' %}">
<meta name="theme-color" content="#ffffff">
<link rel="shortcut icon" href="{% static 'base/imgs/favicon/favicon.ico' %}">
<title>iTool: {{app_name}}</title>
<!-- ===* Bootstrap *=== -->
<link href="{% static 'base/css/heineken-bs.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'base/css/scorecard-font.css' %}" rel="stylesheet" type="text/css">
<!-- Fontawesome -->
<script type="text/javascript" src="{% static 'base/js/jquery-3.1.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'base/js/popper.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'base/css/fontawesome/css/all.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'base/css/material-design-iconic-font.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'base/css/styles.css' %}">

templates/includes/navbar.html
{% load staticfiles %}
{% if logos %}
{% include 'includes/navbar/logos.html' %}
{% endif %}
<!-- ===* Navbar *=== -->
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="padding:2px 1rem;">
  <button class="navbar-toggler navbar-toggler-right collapsed" type="button" data-toggle="collapse" data-target="#nvbrToggler" aria-controls="nvbrToggler" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <span class="navbar-brand text-primary font-weight-normal"><i class="fa fa-user text-primary"></i>&nbsp;Nombre&nbsp;Apellido&nbsp;<span class="font-weight-light text-info"><small>@username</small></span></span>
  <div class="navbar-collapse collapse justify-content-end" id="nvbrToggler">
    <form class="form-inline my-2 my-lg-0 ml-auto mr-4">
      <div class="input-group input-group-sm">
        <input type="text" class="form-control" aria-label="Buscar" style="border-radius:20px 0 0 20px;" placeholder="Buscar...">
        <div class="input-group-append">
          <button type="button" class="btn btn-primary" style="border-radius:0 20px 20px 0;"><i class="fa fa-search fa-lg"></i></button>
        </div>
      </div>
    </form>
    <ul class="navbar-nav mt-2 mt-md-0 justify-content-end">
      <li class="nav-item">
        <a class="nav-link btnregresar" title="Regresar" style="cursor:pointer;">
          <i class="fa fa-reply fa-lg"></i><span class="d-xl-none d-lg-none d-md-none d-sm-none">&nbsp;Regresar</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link btnChat" style="cursor:pointer;" title="Chat">
          <div class="fa-lg">
            <span class="fa-layers fa-fw">
              <i class="fa fa-comment"></i>
              <span class="fa-layers-counter bg-danger numMsgs" style="display:none;transform:scale(.35);"></span>
            </span>
            <span class="d-xl-none d-lg-none d-md-none d-sm-none">&nbsp;Chat</span>
          </div>
        </a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="" id="navbarDrpdwn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-cog fa-lg"></i><span class="d-xl-none d-lg-none d-md-none d-sm-none">&nbsp;Más opciones</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDrpdwn">
          <a class="dropdown-item" href="#">
            <i class="fa fa-question-circle"></i>&nbsp;Ayuda
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <i class="fa fa-lock"></i>&nbsp;Cambiar contraseña
          </a>
          <a class="dropdown-item" href="#">
            <i class="fa fa-wrench"></i>&nbsp;Configuración
          </a>
          <a class="dropdown-item text-danger" href="#" id="DownloadAPK">
            <i class="fa fa-download"></i>&nbsp;Descargar app
          </a>
          <a class="dropdown-item btnSalir" style="cursor:pointer;">
            <i class="fa fa-sign-out-alt"></i>&nbsp;Salir
          </a>
        </div>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>
{% if botones_nav %}
{% include 'includes/navbar/botones_nav.html' %}
{% endif %}

templates/includes/navbar/botones_nav.html
{% load staticfiles %}
<!-- ===* Botones nav *=== -->
<div class="col-12">
  <div class="row no-gutters">
    <div class="col-3">
      <div class="row">
        <div class="btn-group col-12 pl-0" role="group" aria-label="Penetration">
          <a href="{% url 'scorecard:penetration' %}" role="button" class="btn btn-danger btn-collapse active" style="width:30%; border-radius:0;">
            <i class="scorecard-i fa fa-penetration fa-lg"></i>
          </a>
          <a href="{% url 'scorecard:penetration' %}" role="button" class="btn btn-danger text-white" style="width:70%; border-radius:0;">PENETRATION</a>
        </div><!-- /.btn-group -->
      </div><!-- /.row -->
    </div><!-- /.col-3 -->
    <div class="col-3">
      <div class="row">
        <div class="btn-group col-12" role="group" aria-label="Productivity">
          <a href="{% url 'scorecard:productivity' %}" role="button" class="btn btn-success active" style="width:30%; border-radius:0;">
            <i class="scorecard-i fa fa-productivity fa-lg"></i>
          </a>
          <a href="{% url 'scorecard:productivity' %}" role="button" class="btn btn-success text-white" style="width:70%; border-radius:0;">PRODUCTIVITY</a>
        </div><!-- /.btn-group -->
      </div><!-- /.row -->
    </div><!-- /.col-3 -->
    <div class="col-3">
      <div class="row">
        <div class="btn-group col-12" role="group" aria-label="Six">
          <a href="{% url 'scorecard:six' %}" role="button" class="btn btn-primary active" style="width:30%; border-radius:0;">
            <i class="scorecard-i fa fa-six"></i>
          </a>
          <a href="{% url 'scorecard:six' %}" role="button" class="btn btn-primary" style="width:70%; border-radius:0;">SIX</a>
        </div><!-- /.btn-group -->
      </div><!-- /.row -->
    </div><!-- /.col-3 -->
    <div class="col-3">
      <div class="row">
        <div class="btn-group col-12 pr-0" role="group" aria-label="Assortment">
          <a href="{% url 'scorecard:assortment' %}" role="button" class="btn btn-dark active" style="width:30%; border-radius:0;">
            <i class="scorecard-i fa fa-assortment fa-lg"></i>
          </a>
          <a href="{% url 'scorecard:assortment' %}" role="button" class="btn btn-dark" style="width:70%; border-radius:0;">ASSORTMENT</a>
        </div><!-- /.btn-group -->
      </div><!-- /.row -->
    </div><!-- /.col-3 -->  
  </div><!-- /.row -->
</div><!-- /.col-12 -->

templates/includes/navbar/logos.html
{% load staticfiles %}
<!-- ===* Logos *=== -->
<div class="col-12 bg-white">
  <div class="row justify-content-between" style="height:65px;">
    <div class="col-xl-2 col-lg-2 col-md-4 col-sm-6 col-6" style="margin-top:15px;">
      <object type="image/svg+xml" data="{% static 'base/imgs/logo-itool.svg' %}" style="max-height:35px;"></object>
    </div><!-- /.col-2 -->
    <div class="col-xl-2 col-lg-2 col-md-4 col-sm-6 col-6" style="margin-top:15px;">
      <object type="image/svg+xml" data="{% static 'base/imgs/logo-heineken-cm.svg' %}" style="max-height:35px;"></object>
    </div><!-- /.col-2 -->
  </div><!-- /.row -->
</div><!-- /.col-12 -->

templates/includes/scripts.html
{% load staticfiles %}
<!-- ===* JS *=== -->
<script type="text/javascript" src="{% static 'base/js/bootstrap.min.js' %}"></script>

templates/includes/titulo.html
{% load staticfiles %}
<div class="row">
  <div class="col-12 titulo">
    <h2>{{titulo}}</h2>
    <p class="lead">{{subtitulo}}</p>
  </div><!-- /.col-12 -->
</div><!-- /.row -->